### PR TITLE
Update servers.json

### PR DESCRIPTION
**Pull request by mexican1973**
Added new official running servers. Please merge into master. Thanks. Heinrich.

### CODE REVIEW

**Comment by Achieveaholics** [comment]
@mexican1973  I tried putting in all these servers and my Electrum Wallet still won't connect. Is there server updates or anything?

**Comment by NATURALCOIN** [comment]
@mexican1973 I would recommend coming over to this thread since it is specifically focused on the Electrum wallet not connecting (https://github.com/z-classic/electrum-zcl/issues/194)

**Comment by NATURALCOIN** [comment]
@mexican1973 I would recommend coming over to the other thread since its specifically titled ZClassic Electrum 1.0.6 Server Lagging / Not Connecting. I would post the link but github is blocking me from doing that because of "merging is blocked."

**Review by BlockchainJames — APPROVED** [review]

**Comment by mexican1973** [comment]
new updated version now at  community github:
https://github.com/ZclassicCommunity/electrum-zcl

**Pull request closed without merging**
