### PR TITLE
Fix Currency Rate to show USD or EUR

### PR DESCRIPTION
**Pull request by ghost**
I wanted Euro's to show in my client. The option currently doesn't work, so this fixes that. 
It's Temporary, as it looks like CMC will deprecate the current API's in favour of a new API key based 'Pro API' in December (Maybe the current API will be around for much longer though)  - Will look for alternatives.

### CODE REVIEW

**Comment by VictorLux** [comment]
coingecko has a free api with enough data, perhaps a good alternative, onchainfx does not have yet an API.

**Comment by ghost** [comment]
Sure. Though, in the meantime, accept this ;)

**Comment by nimbosa** [comment]
@thedevworks this is good, i was wondering why this doesn't work, too! Thanks..

but do we need to remove CNY? is there no free data available?

**Comment by ghost** [comment]
You can get CNY but currently the way it is, you select EUR and it gives you EUR and USD in 1 call. Calling the API with different params for different currencies has been crippled in this Electrum a long time ago for some reason. Since this was a temporary solution I figured it was best working with 2 currencies than not working at all!

**Pull request closed without merging**
